const PROMPTS = [
  "Worst thing to say on a first date",
  "Fastest way to get fired in 10 seconds",
  "What not to say at a funeral",
  "Worst lie to tell your parents",
  "Most awkward wedding toast",
  "Terrible advice for a job interview",
  "What not to say to a police officer",
  "Worst excuse for being late",
  "Things you shouldn't say to your doctor",
  "Bad pickup line at a library",
  "Worst thing to yell in a movie theater",
  "Terrible baby name suggestion",
  "What not to say during a breakup",
  "Worst conversation starter at a party",
  "Bad thing to say when meeting your partner's parents",
  "Worst thing to say when you trip in public",
  "Worst thing to shout when the lights go out",
  "Worst thing to say when your friend gets caught lying",
  "Worst thing to say when someone posts a selfie",
  "Worst thing to yell when WiFi disconnects",
  "Worst thing to say when food arrives late",
  "Worst thing to say when the teacher says 'Who did this?'",
  "Worst thing to say when the mic turns on by accident",
  "Worst thing to say when your crush enters the room",
  "Worst thing to say when your mom checks your phone",
  "Worst thing to shout in the middle of a wedding",
  "Worst thing to say when your friend says 'Trust me'",
  "Worst thing to say when you lose a game you bragged about",
  "Worst thing to say when someone says 'Be honest'",
  "Worst thing to say when you hear sirens",
  "Worst thing to say when someone says 'I have bad news'",
  "Worst thing to say when someone starts crying",
  "Worst thing to say when someone says 'I'm on my way'",
  "Worst thing to say when food falls on the floor",
  "Worst thing to say when your friend gets roasted",
  "Worst thing to say when your teacher mispronounces your name",
  "Worst thing to say when the camera accidentally turns on",
  "Worst thing to say when you walk into the wrong class",
  "Worst thing to say when someone says 'Don't tell anyone'",
  "Worst thing to say when your friend gets a haircut",
  "Worst thing to say when someone says 'Guess what'",
  "Worst thing to say when your joke doesn't land",
  "Worst thing to say when your friend is flexing",
  "Worst thing to say when your friend is already embarrassed",
  "Worst thing to say when everyone is silent",
  "Worst thing to say when the bill arrives",
  "Worst thing to say when your friend says 'I'm outside'",
  "Worst thing to say when your phone dies at 1%",
  "Worst thing to say when someone wins after talking trash",
  "Worst thing to say when someone sends a voice note",
  "Worst thing to say when your friend is clearly lying",
  "Worst thing to say when your friend says 'Rate me honestly'",
  "Worst thing to say when your parents are in the next room",
  "Worst thing to say when someone says 'Don't panic'",
  "Worst thing to say when someone drops their phone",
  "Worst thing to say when someone says 'I have tea'",
  "Worst thing to say when your friend starts a story with 'So basically…'",
  "Worst thing to say when someone gets exposed",
  "Worst thing to say when your food tastes terrible",
  "Worst thing to say when someone says 'Act normal'",
  "Worst thing to say when someone sends a risky message by mistake",
  "Worst thing to say when someone starts over-explaining",
  "Worst thing to say when your friend is clearly coping",
  "Worst thing to say when your friend says 'Don't judge me'",
  "Worst thing to say when everyone is waiting for your answer",
  "Worst thing to say when someone says 'It's not that deep'",
  "Worst thing to say when your friend is already mad",
  "Worst thing to say when someone says 'Promise me'",
  "Worst thing to say when your friend says 'Be supportive'",
  "Worst thing to say when someone gets called to the front",
  "Worst thing to say when your friend says 'Hear me out'",
  "Worst thing to say when someone says 'I practiced this'",
  "Worst thing to say when your friend is being dramatic",
  "Worst thing to say when someone sends a long paragraph",
  "Worst thing to say when someone says 'Don't laugh'",
  "Worst thing to say when someone brags too much",
  "Worst thing to say when your friend says 'I'm built different'",
  "Worst thing to say when your friend is clearly wrong",
  "Worst thing to say when someone gets second-hand embarrassment",
  "Worst thing to say when someone takes a risky sip",
  "Worst thing to say when someone says 'Nobody saw that'",
  "Worst thing to say when your friend says 'It's fine'",
  "Worst thing to say when someone sends a risky screenshot",
  "Worst thing to say when someone says 'This is between us'",
  "Worst thing to say when someone is already being clowned",
  "Worst thing to say when your friend gets roasted in public",
  "Worst thing to say when your friend starts fake acting",
  "Worst thing to say when someone misses an obvious joke",
  "Worst thing to say when your friend tries to be mysterious",
  "Worst thing to say when someone says 'Don't tell my mom'",
  "Worst thing to say when your friend is hyping themselves",
  "Worst thing to say when someone gets caught screen-recording",
  "Worst thing to say when someone says 'I wasn't ready'",
  "Worst thing to say when someone says 'Relax'",
  "Worst thing to say when your friend tries to flirt",
  "Worst thing to say when someone sends '…'",
  "Worst thing to say when someone says 'I'm serious this time'",
  "Worst thing to say when someone says 'That's confidential'",
  "Worst thing to say when someone gets karma instantly",
  "Worst thing to say when someone is lying confidently",
  "Worst thing to say when your friend is trying to look cool",
  "Worst thing to say when someone says 'Trust the process'",
  "Worst thing to say when someone says 'This can't get worse'",
  "Worst thing to say when your friend says 'Don't clip this'",
  "Worst thing to say when someone is in denial",
  "Worst thing to say when someone says 'This is my villain origin'",
  "Worst thing to say when your friend says 'I'm not embarrassed'",
  "Worst thing to say when someone says 'Don't screenshot'",
  "Worst thing to say when your friend says 'Act surprised'",
  "Worst thing to say when someone is already losing",
  "Worst thing to say when your friend gets humbled",
  "Worst thing to say when someone says 'I regret this already'",
  "Worst thing to say when someone says 'This is a bad idea'",
  "Worst thing to say when someone gets second-hand roasted",
  "Worst thing to say when your friend says 'Bro stop'",
];

export function getRandomPrompt(): string {
  const idx = Math.floor(Math.random() * PROMPTS.length);
  return PROMPTS[idx];
}
